name: Prototyping_UOS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.12.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.4.0
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pysocks=1.7.1
  - python=3.9.19
  - python_abi=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.4.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - albumentations==1.3.0
    - attrs==23.2.0
    - av==12.0.0
    - branca==0.8.1
    - cffi==1.16.0
    - click==8.1.7
    - contourpy==1.2.1
    - controlnet-aux==0.0.7
    - cycler==0.12.1
    - diffusers==0.24.0
    - einops==0.7.0
    - et-xmlfile==2.0.0
    - face-alignment==1.4.1
    - facexlib==0.3.0
    - filterpy==1.4.5
    - flatbuffers==24.3.25
    - folium==0.20.0
    - fonttools==4.51.0
    - fsspec==2024.3.1
    - ftfy==6.2.0
    - grpcio==1.62.1
    - huggingface-hub==0.22.2
    - imageio==2.34.0
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.0
    - jax==0.4.26
    - jaxlib==0.4.26
    - kiwisolver==1.4.5
    - lazy-loader==0.4
    - llvmlite==0.42.0
    - lmdb==1.4.1
    - lpips==0.1.4
    - markdown==3.6
    - markdown-it-py==3.0.0
    - matplotlib==3.8.4
    - mdurl==0.1.2
    - mediapipe==0.10.11
    - ml-dtypes==0.4.0
    - mmagic==1.0.1
    - mmcls==1.0.0rc6
    - mmcv==2.0.1
    - mmdet==3.0.0
    - mmengine==0.8.5
    - mmpretrain==1.0.0rc7
    - mmsegmentation==1.0.0
    - model-index==0.1.11
    - modelindex==0.0.2
    - numba==0.59.1
    - opencv-contrib-python==4.9.0.80
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.11.0.86
    - openpyxl==3.1.5
    - opt-einsum==3.3.0
    - ordered-set==4.1.0
    - pandas==2.2.1
    - pip==25.1.1
    - platformdirs==4.2.0
    - prettytable==3.10.0
    - protobuf==3.20.3
    - psutil==5.9.8
    - pycocotools==2.0.7
    - pycparser==2.22
    - pygments==2.17.2
    - pyparsing==3.1.2
    - pyside6==6.9.2
    - pyside6-addons==6.9.2
    - pyside6-essentials==6.9.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - qudida==0.0.4
    - regex==2023.12.25
    - resize-right==0.0.2
    - rich==13.7.1
    - safetensors==0.4.2
    - scikit-image==0.22.0
    - scipy==1.13.0
    - shapely==2.0.3
    - shiboken6==6.9.2
    - slidingwindow==0.0.14
    - sounddevice==0.4.6
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - termcolor==2.4.0
    - terminaltables==3.1.10
    - tifffile==2024.2.12
    - timm==0.9.16
    - tokenizers==0.15.2
    - tomli==2.0.1
    - tqdm==4.66.2
    - transformers==4.39.3
    - tzdata==2024.1
    - werkzeug==3.0.2
    - xyzservices==2025.4.0
    - yapf==0.40.2
    - zipp==3.18.1
prefix: /home/user/anaconda3/envs/PT
